#[cfg(feature = "test")]
pub fn main() {
    use crdt_range::test_utils::{fuzzing, Action, AnnotationType};
    use Action::*;
    use AnnotationType::*;

    fuzzing(
        2,
        vec![
            Insert {
                actor: 190,
                pos: 43,
                len: 190,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnLink,
            },
            Sync(255, 255),
            Annotate {
                actor: 83,
                pos: 255,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 128,
                pos: 183,
                len: 190,
                annotation: Bold,
            },
            Insert {
                actor: 190,
                pos: 49,
                len: 190,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 35,
                annotation: Bold,
            },
            Annotate {
                actor: 46,
                pos: 0,
                len: 43,
                annotation: Link,
            },
            Sync(7, 43),
            Annotate {
                actor: 43,
                pos: 190,
                len: 255,
                annotation: Link,
            },
            Annotate {
                actor: 158,
                pos: 255,
                len: 255,
                annotation: UnLink,
            },
            Annotate {
                actor: 190,
                pos: 83,
                len: 255,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Insert {
                actor: 190,
                pos: 190,
                len: 186,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 66,
                len: 65,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnLink,
            },
            Annotate {
                actor: 83,
                pos: 255,
                len: 190,
                annotation: Bold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 191,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 158,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 66,
                pos: 65,
                len: 66,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnLink,
            },
            Delete {
                actor: 255,
                pos: 190,
                len: 190,
            },
            Sync(26, 190),
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 186,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 186,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 158,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Sync(255, 255),
            Sync(255, 255),
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 191,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 191,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 158,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 156,
                pos: 156,
                len: 156,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: Link,
            },
            Insert {
                actor: 11,
                pos: 11,
                len: 11,
            },
            Insert {
                actor: 11,
                pos: 11,
                len: 11,
            },
            Insert {
                actor: 11,
                pos: 11,
                len: 11,
            },
            Insert {
                actor: 11,
                pos: 11,
                len: 11,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 186,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 158,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Sync(255, 255),
            Sync(255, 106),
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 191,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 186,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 191,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: Link,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 158,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Delete {
                actor: 255,
                pos: 255,
                len: 61,
            },
            Sync(190, 190),
            Insert {
                actor: 0,
                pos: 190,
                len: 190,
            },
            Annotate {
                actor: 62,
                pos: 255,
                len: 255,
                annotation: Bold,
            },
            Sync(190, 190),
            Annotate {
                actor: 190,
                pos: 13,
                len: 13,
                annotation: Link,
            },
            Insert {
                actor: 128,
                pos: 190,
                len: 190,
            },
            Annotate {
                actor: 252,
                pos: 26,
                len: 26,
                annotation: Link,
            },
            Annotate {
                actor: 190,
                pos: 128,
                len: 26,
                annotation: Link,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Annotate {
                actor: 190,
                pos: 196,
                len: 46,
                annotation: Bold,
            },
            Annotate {
                actor: 190,
                pos: 126,
                len: 190,
                annotation: Link,
            },
            Delete {
                actor: 81,
                pos: 81,
                len: 81,
            },
            Delete {
                actor: 81,
                pos: 81,
                len: 81,
            },
            Delete {
                actor: 81,
                pos: 81,
                len: 81,
            },
            Delete {
                actor: 81,
                pos: 81,
                len: 81,
            },
            Delete {
                actor: 81,
                pos: 81,
                len: 57,
            },
            Insert {
                actor: 190,
                pos: 62,
                len: 255,
            },
            Sync(61, 0),
            Annotate {
                actor: 190,
                pos: 128,
                len: 57,
                annotation: Link,
            },
            Annotate {
                actor: 41,
                pos: 0,
                len: 38,
                annotation: UnBold,
            },
            Annotate {
                actor: 128,
                pos: 252,
                len: 26,
                annotation: Link,
            },
            Sync(190, 190),
            Insert {
                actor: 14,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 47,
                pos: 190,
                len: 183,
            },
            Insert {
                actor: 57,
                pos: 55,
                len: 48,
            },
            Insert {
                actor: 190,
                pos: 49,
                len: 190,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 35,
                annotation: Bold,
            },
            Annotate {
                actor: 62,
                pos: 255,
                len: 255,
                annotation: Bold,
            },
            Sync(190, 190),
            Annotate {
                actor: 190,
                pos: 13,
                len: 13,
                annotation: Link,
            },
            Insert {
                actor: 128,
                pos: 190,
                len: 190,
            },
            Annotate {
                actor: 252,
                pos: 26,
                len: 26,
                annotation: Link,
            },
            Annotate {
                actor: 190,
                pos: 128,
                len: 26,
                annotation: Link,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 47,
                pos: 190,
                len: 183,
            },
            Insert {
                actor: 56,
                pos: 128,
                len: 190,
            },
            Annotate {
                actor: 128,
                pos: 252,
                len: 26,
                annotation: Link,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 30,
                len: 30,
                annotation: Link,
            },
            Insert {
                actor: 30,
                pos: 30,
                len: 30,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 1,
                len: 26,
                annotation: Link,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Annotate {
                actor: 183,
                pos: 190,
                len: 190,
                annotation: Bold,
            },
            Insert {
                actor: 57,
                pos: 190,
                len: 49,
            },
            Sync(111, 255),
            Insert {
                actor: 0,
                pos: 255,
                len: 190,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 13,
                annotation: Comment,
            },
            Insert {
                actor: 57,
                pos: 128,
                len: 190,
            },
            Annotate {
                actor: 128,
                pos: 252,
                len: 26,
                annotation: Link,
            },
            Sync(255, 255),
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 196,
                annotation: Link,
            },
            Insert {
                actor: 190,
                pos: 49,
                len: 190,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: Link,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnLink,
            },
            Delete {
                actor: 66,
                pos: 66,
                len: 66,
            },
            Annotate {
                actor: 189,
                pos: 172,
                len: 172,
                annotation: Bold,
            },
            Delete {
                actor: 189,
                pos: 189,
                len: 66,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 189,
                annotation: UnBold,
            },
            Insert {
                actor: 0,
                pos: 66,
                len: 66,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: Bold,
            },
            Insert {
                actor: 190,
                pos: 62,
                len: 255,
            },
            Sync(61, 0),
            Annotate {
                actor: 190,
                pos: 128,
                len: 57,
                annotation: Link,
            },
            Annotate {
                actor: 41,
                pos: 0,
                len: 38,
                annotation: UnBold,
            },
            Annotate {
                actor: 128,
                pos: 252,
                len: 26,
                annotation: Link,
            },
            Sync(190, 190),
            Insert {
                actor: 14,
                pos: 0,
                len: 0,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 26,
            },
            Insert {
                actor: 26,
                pos: 26,
                len: 47,
            },
            Annotate {
                actor: 196,
                pos: 46,
                len: 57,
                annotation: Bold,
            },
            Annotate {
                actor: 126,
                pos: 190,
                len: 190,
                annotation: Bold,
            },
            Annotate {
                actor: 57,
                pos: 60,
                len: 190,
                annotation: Comment,
            },
            Insert {
                actor: 0,
                pos: 0,
                len: 255,
            },
            Insert {
                actor: 128,
                pos: 13,
                len: 0,
            },
            Insert {
                actor: 57,
                pos: 190,
                len: 128,
            },
            Insert {
                actor: 57,
                pos: 128,
                len: 190,
            },
            Annotate {
                actor: 128,
                pos: 252,
                len: 26,
                annotation: Link,
            },
            Annotate {
                actor: 183,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
            Insert {
                actor: 0,
                pos: 184,
                len: 190,
            },
            Annotate {
                actor: 57,
                pos: 57,
                len: 57,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 66,
                len: 66,
                annotation: UnBold,
            },
            Insert {
                actor: 189,
                pos: 189,
                len: 189,
            },
            Insert {
                actor: 189,
                pos: 189,
                len: 189,
            },
            Annotate {
                actor: 189,
                pos: 184,
                len: 189,
                annotation: UnBold,
            },
            Annotate {
                actor: 189,
                pos: 189,
                len: 190,
                annotation: UnBold,
            },
            Annotate {
                actor: 190,
                pos: 190,
                len: 190,
                annotation: UnBold,
            },
        ],
    );
}

#[cfg(not(feature = "test"))]
fn main() {}
